###
POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZjkwOWVjMi1jMDNkLTQ4YTItOTMyMi0zYzVjOWQ2NzFlOTkiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NjM0OTk1NH0.Cv972VNlX9Z_2yfLtPmz6kvBKTJQNFPKu946cWYhpNw

{
  "title": "Curso de JavaScript",
  "description": "Aprenda JavaScript do zero"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZjkwOWVjMi1jMDNkLTQ4YTItOTMyMi0zYzVjOWQ2NzFlOTkiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NjM0OTk1NH0.Cv972VNlX9Z_2yfLtPmz6kvBKTJQNFPKu946cWYhpNw

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "fabricia@bol.com",
  "password": "123456",
  "role": "manager"
}

###
GET http://localhost:3333/users/b02b5b23-1ce6-4d27-b48c-0b171cfac0ab
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YzI4MGNhMi0xNjdlLTRjZDEtOTBjOC1kODM4NmEzNmVlOWYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjI1MTQ1OH0.Aa35k2rArOXPg1QqqVAYKqD7JdyL19ONf752L0SZx9g

###
GET http://localhost:3333/users?orderBy=name

###
POST http://localhost:3333/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YzI4MGNhMi0xNjdlLTRjZDEtOTBjOC1kODM4NmEzNmVlOWYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjI1MTQ1OH0.Aa35k2rArOXPg1QqqVAYKqD7JdyL19ONf752L0SZx9g

{
  "name": "Teste user3",
  "email": "fabricia@bol.com",
  "password": "123456",
  "role": "manager"
}
