###
POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTEzMjkyMC0wYmNhLTQ1NjEtOGQzMC0wN2IxOTc4Yzk5Y2MiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTIxNDAwNH0.NshpGUH8kPUSmZJOz2DqhyYW0EOiA-HzYHnikz_PXaU

{
  "title": "Curso de Next.js"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/6c2ea3d8-21b0-4fd9-a179-67c0615fba13
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTEzMjkyMC0wYmNhLTQ1NjEtOGQzMC0wN2IxOTc4Yzk5Y2MiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NTIxMzEwN30.oLv9EnuNBZi6jOii-n-rUPahGnjO2mLAqXsW0c5H_5E

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Fabricia_Costa@bol.com.br",
  "password": "123456"
}